env:
  browser: true
  es2021: true
extends:
  - airbnb-typescript
  - airbnb/hooks
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
  files:
    - '*.ts'
    - '*.tsx'
  project: tsconfig.json
plugins:
  - react
  - '@typescript-eslint'
rules:
  comma-dangle:
    - error
    - only-multiline
  import/no-cycle: off
  '@typescript-eslint/explicit-function-return-type': 'off'
  '@typescript-eslint/no-unused-vars': warn
  linebreak-style: 'off'
  import/no-unresolved: 'off'
  import/extensions: 'off'
  import/no-extraneous-dependencies:
    [
      'error',
      {
        'devDependencies': true,
        'optionalDependencies': true,
        'peerDependencies': true,
      },
    ]
  import/prefer-default-export:
    - 'off'
    - extensions:
        - '.ts'
  react/jsx-filename-extension:
    - 'off'
    - extensions:
        - '.js'
        - '.jsx'
  react/destructuring-assignment: 'off'
  jsx-a11y/no-static-element-interactions: 'off'
  prefer-template: 'off'
  no-plusplus: 'off'
  eol-last: 'off'
  react/prop-types: 'off'
  arrow-parens:
    - Error
    - as-needed
  max-len:
    - error
    - code: 135
  no-empty-function: warn
  no-empty: warn
  '@typescript-eslint/no-empty-function': warn
  prefer-destructuring: 'off'
  jsx-a11y/click-events-have-key-events: off
  react-hooks/rules-of-hooks: off
  react/require-default-props: off
  react/jsx-props-no-spreading: off
