version: '3.1'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
        # copies SQL script to create example tables
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
        # copies SQL script to fill example tables
      - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
